apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- generated/role.yaml
patches:
- target:
    group: rbac.authorization.k8s.io
    kind: Role
  patch: |-
    - op: remove
      path: /metadata/namespace
